plugins { id 'com.android.application' }

android {
    namespace 'com.sahar.mushaf'
    compileSdk 34

    defaultConfig {
        applicationId "com.sahar.mushaf"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "2.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { }
